
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Joshua C. Magoliman
 */
public class JFrame_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Calculator
     */
    
    // <editor-fold defaultstate="collapsed" desc="Fields">
    private double firstNum, secondNum, answer;
    private char arithmeticOperator;
    private boolean isDotButtonClicked, isNumericButtonClicked;
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Constructor">
    public JFrame_Calculator() {
        // Invoke the Built-in Method called initComponents()
        initComponents();
        // Invoke the User Defined Method called setIcon()
        setIcon();
        // Invoke the User Defined Method called reset()
        reset();
    }
    // </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_Main = new javax.swing.JPanel();
        jbtn_Clear = new javax.swing.JButton();
        jtxtfield_Display = new javax.swing.JTextField();
        jbtn_Dot = new javax.swing.JButton();
        jbtn_One = new javax.swing.JButton();
        jbtn_Plus = new javax.swing.JButton();
        jbtn_Two = new javax.swing.JButton();
        jbtn_Minus = new javax.swing.JButton();
        jbtn_Three = new javax.swing.JButton();
        jbtn_Mutiply = new javax.swing.JButton();
        jbtn_Four = new javax.swing.JButton();
        jbtn_Divide = new javax.swing.JButton();
        jbtn_Five = new javax.swing.JButton();
        jbtn_Six = new javax.swing.JButton();
        jbtn_Equal = new javax.swing.JButton();
        jbtn_Seven = new javax.swing.JButton();
        jbtn_Nine = new javax.swing.JButton();
        jbtn_Eight = new javax.swing.JButton();
        jbtn_Zero = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbtn_Close = new javax.swing.JButton();
        jbtn_Minimize = new javax.swing.JButton();
        jbtn_PositiveOrNegative = new javax.swing.JButton();
        jlbl_Title = new javax.swing.JLabel();
        jbtn_Erase = new javax.swing.JButton();
        jbtn_CopyToClipBoard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMPLECALCULATOR");
        setUndecorated(true);
        setResizable(false);

        jpanel_Main.setBackground(new java.awt.Color(202, 202, 202));

        jbtn_Clear.setBackground(new java.awt.Color(2, 20, 121));
        jbtn_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Clear.setForeground(java.awt.Color.white);
        jbtn_Clear.setText("CLEAR");
        jbtn_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Clear.setFocusable(false);
        jbtn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ClearActionPerformed(evt);
            }
        });

        jtxtfield_Display.setEditable(false);
        jtxtfield_Display.setBackground(java.awt.Color.black);
        jtxtfield_Display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfield_Display.setForeground(java.awt.Color.white);
        jtxtfield_Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtfield_Display.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtn_Dot.setBackground(java.awt.Color.black);
        jbtn_Dot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Dot.setForeground(java.awt.Color.white);
        jbtn_Dot.setText(".");
        jbtn_Dot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Dot.setFocusable(false);
        jbtn_Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DotActionPerformed(evt);
            }
        });

        jbtn_One.setBackground(java.awt.Color.black);
        jbtn_One.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_One.setForeground(java.awt.Color.white);
        jbtn_One.setText("1");
        jbtn_One.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_One.setFocusable(false);
        jbtn_One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_OneActionPerformed(evt);
            }
        });

        jbtn_Plus.setBackground(new java.awt.Color(102, 13, 167));
        jbtn_Plus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Plus.setForeground(java.awt.Color.white);
        jbtn_Plus.setText("+");
        jbtn_Plus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Plus.setFocusable(false);
        jbtn_Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_PlusActionPerformed(evt);
            }
        });

        jbtn_Two.setBackground(java.awt.Color.black);
        jbtn_Two.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Two.setForeground(java.awt.Color.white);
        jbtn_Two.setText("2");
        jbtn_Two.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Two.setFocusable(false);
        jbtn_Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_TwoActionPerformed(evt);
            }
        });

        jbtn_Minus.setBackground(new java.awt.Color(102, 13, 167));
        jbtn_Minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_Minus.setForeground(java.awt.Color.white);
        jbtn_Minus.setText("-");
        jbtn_Minus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Minus.setFocusable(false);
        jbtn_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_MinusActionPerformed(evt);
            }
        });

        jbtn_Three.setBackground(java.awt.Color.black);
        jbtn_Three.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Three.setForeground(java.awt.Color.white);
        jbtn_Three.setText("3");
        jbtn_Three.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Three.setFocusable(false);
        jbtn_Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ThreeActionPerformed(evt);
            }
        });

        jbtn_Mutiply.setBackground(new java.awt.Color(102, 13, 167));
        jbtn_Mutiply.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Mutiply.setForeground(java.awt.Color.white);
        jbtn_Mutiply.setText("x");
        jbtn_Mutiply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Mutiply.setFocusable(false);
        jbtn_Mutiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_MutiplyActionPerformed(evt);
            }
        });

        jbtn_Four.setBackground(java.awt.Color.black);
        jbtn_Four.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Four.setForeground(java.awt.Color.white);
        jbtn_Four.setText("4");
        jbtn_Four.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Four.setFocusable(false);
        jbtn_Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_FourActionPerformed(evt);
            }
        });

        jbtn_Divide.setBackground(new java.awt.Color(102, 13, 167));
        jbtn_Divide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Divide.setForeground(java.awt.Color.white);
        jbtn_Divide.setText("/");
        jbtn_Divide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Divide.setFocusable(false);
        jbtn_Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DivideActionPerformed(evt);
            }
        });

        jbtn_Five.setBackground(java.awt.Color.black);
        jbtn_Five.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Five.setForeground(java.awt.Color.white);
        jbtn_Five.setText("5");
        jbtn_Five.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Five.setFocusable(false);
        jbtn_Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_FiveActionPerformed(evt);
            }
        });

        jbtn_Six.setBackground(java.awt.Color.black);
        jbtn_Six.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Six.setForeground(java.awt.Color.white);
        jbtn_Six.setText("6");
        jbtn_Six.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Six.setFocusable(false);
        jbtn_Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SixActionPerformed(evt);
            }
        });

        jbtn_Equal.setBackground(new java.awt.Color(8, 102, 0));
        jbtn_Equal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_Equal.setForeground(java.awt.Color.white);
        jbtn_Equal.setText("=");
        jbtn_Equal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Equal.setFocusable(false);
        jbtn_Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_EqualActionPerformed(evt);
            }
        });

        jbtn_Seven.setBackground(java.awt.Color.black);
        jbtn_Seven.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Seven.setForeground(java.awt.Color.white);
        jbtn_Seven.setText("7");
        jbtn_Seven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Seven.setFocusable(false);
        jbtn_Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SevenActionPerformed(evt);
            }
        });

        jbtn_Nine.setBackground(java.awt.Color.black);
        jbtn_Nine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Nine.setForeground(java.awt.Color.white);
        jbtn_Nine.setText("9");
        jbtn_Nine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Nine.setFocusable(false);
        jbtn_Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_NineActionPerformed(evt);
            }
        });

        jbtn_Eight.setBackground(java.awt.Color.black);
        jbtn_Eight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Eight.setForeground(java.awt.Color.white);
        jbtn_Eight.setText("8");
        jbtn_Eight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Eight.setFocusable(false);
        jbtn_Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_EightActionPerformed(evt);
            }
        });

        jbtn_Zero.setBackground(java.awt.Color.black);
        jbtn_Zero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Zero.setForeground(java.awt.Color.white);
        jbtn_Zero.setText("0");
        jbtn_Zero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Zero.setFocusable(false);
        jbtn_Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ZeroActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.black);

        jbtn_Close.setBackground(java.awt.Color.darkGray);
        jbtn_Close.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtn_Close.setForeground(java.awt.Color.white);
        jbtn_Close.setText("X");
        jbtn_Close.setFocusable(false);
        jbtn_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CloseActionPerformed(evt);
            }
        });

        jbtn_Minimize.setBackground(java.awt.Color.darkGray);
        jbtn_Minimize.setForeground(java.awt.Color.white);
        jbtn_Minimize.setText("-");
        jbtn_Minimize.setFocusable(false);
        jbtn_Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_MinimizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_Minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtn_Close)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jbtn_PositiveOrNegative.setBackground(java.awt.Color.black);
        jbtn_PositiveOrNegative.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_PositiveOrNegative.setForeground(java.awt.Color.white);
        jbtn_PositiveOrNegative.setText("+ -");
        jbtn_PositiveOrNegative.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_PositiveOrNegative.setFocusable(false);
        jbtn_PositiveOrNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_PositiveOrNegativeActionPerformed(evt);
            }
        });

        jlbl_Title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbl_Title.setForeground(java.awt.Color.black);
        jlbl_Title.setText("SIMPLE CALCULATOR");

        jbtn_Erase.setBackground(new java.awt.Color(145, 25, 0));
        jbtn_Erase.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_Erase.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_Erase.setText("X");
        jbtn_Erase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_Erase.setFocusable(false);
        jbtn_Erase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_EraseActionPerformed(evt);
            }
        });

        jbtn_CopyToClipBoard.setBackground(java.awt.Color.black);
        jbtn_CopyToClipBoard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_CopyToClipBoard.setForeground(java.awt.Color.white);
        jbtn_CopyToClipBoard.setText("COPY TO CLIPBOARD");
        jbtn_CopyToClipBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_CopyToClipBoard.setFocusable(false);
        jbtn_CopyToClipBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_CopyToClipBoardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_MainLayout = new javax.swing.GroupLayout(jpanel_Main);
        jpanel_Main.setLayout(jpanel_MainLayout);
        jpanel_MainLayout.setHorizontalGroup(
            jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_MainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_MainLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtn_One, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_Four, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_MainLayout.createSequentialGroup()
                                .addComponent(jbtn_Two, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn_Three, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanel_MainLayout.createSequentialGroup()
                                .addComponent(jbtn_Five, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn_Six, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn_Plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_MainLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jtxtfield_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_MainLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_MainLayout.createSequentialGroup()
                                .addComponent(jbtn_Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbtn_Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanel_MainLayout.createSequentialGroup()
                                .addComponent(jbtn_Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_MainLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jbtn_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_MainLayout.createSequentialGroup()
                                .addComponent(jbtn_Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn_Mutiply, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanel_MainLayout.createSequentialGroup()
                                .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_PositiveOrNegative, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_Erase, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_Clear)))))
                    .addGroup(jpanel_MainLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jlbl_Title)))
                .addGap(23, 23, 23))
            .addGroup(jpanel_MainLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jbtn_CopyToClipBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_MainLayout.setVerticalGroup(
            jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_MainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbl_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtfield_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_One, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Two, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Three, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Five, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Four, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Six, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn_Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn_Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn_Mutiply, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn_Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_PositiveOrNegative, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Erase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_CopyToClipBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Event Handler Methods (Default Naming Convention)">
    private void jbtn_MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_MinimizeActionPerformed
        // Minimize this Application
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jbtn_MinimizeActionPerformed
    private void jbtn_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CloseActionPerformed
        // Terminate this Application
        System.exit(0);
    }//GEN-LAST:event_jbtn_CloseActionPerformed

    private void jbtn_OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_OneActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 1
        validation(1);
    }//GEN-LAST:event_jbtn_OneActionPerformed
    private void jbtn_TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_TwoActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 2
        validation(2);
    }//GEN-LAST:event_jbtn_TwoActionPerformed
    private void jbtn_ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ThreeActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 3
        validation(3);
    }//GEN-LAST:event_jbtn_ThreeActionPerformed
    private void jbtn_FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_FourActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 4
        validation(4);
    }//GEN-LAST:event_jbtn_FourActionPerformed
    private void jbtn_FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_FiveActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 5
        validation(5);
    }//GEN-LAST:event_jbtn_FiveActionPerformed
    private void jbtn_SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SixActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 6
        validation(6);
    }//GEN-LAST:event_jbtn_SixActionPerformed
    private void jbtn_SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SevenActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 7
        validation(7);
    }//GEN-LAST:event_jbtn_SevenActionPerformed
    private void jbtn_EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_EightActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 8
        validation(8);
    }//GEN-LAST:event_jbtn_EightActionPerformed
    private void jbtn_NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_NineActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 9
        validation(9);
    }//GEN-LAST:event_jbtn_NineActionPerformed
    private void jbtn_ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ZeroActionPerformed
        // Invoke the User Defined Method Called validation() and pass an argument of 0
        validation(0);
    }//GEN-LAST:event_jbtn_ZeroActionPerformed
    private void jbtn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ClearActionPerformed
        // Invoke the User Defined Method called reset()
        reset();
    }//GEN-LAST:event_jbtn_ClearActionPerformed
    private void jbtn_DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DotActionPerformed
        // If the value of field called isjbtnDotClicked is false
        if (isDotButtonClicked == false) {
            // Assign the value in field called isjbtnDotClicked to true
            isDotButtonClicked = true;
        }
        // Get the text of jTextField called jtxtfield_Display and add "."
        jtxtfield_Display.setText(jtxtfield_Display.getText() + jbtn_Dot.getText());
    }//GEN-LAST:event_jbtn_DotActionPerformed
    private void jbtn_PositiveOrNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_PositiveOrNegativeActionPerformed
        // If the text value of jTextField called jtxtfield_Display don't contain ","
        if (!jtxtfield_Display.getText().contains(".")) {
            // Declare a local variable called positiveOrNegativeInteger
            int positiveOrNegativeInteger;
            // Declare a local variable called positiveOrNegativeDouble
            double positiveOrNegativeDouble;

            // If the value of field called isDotButtonClicked is false
            if (isDotButtonClicked == false) {
                // Assign the value of local variable called positiveOrNegativeInteger to the converted value from string to integer 
                positiveOrNegativeInteger = Integer.parseInt(jtxtfield_Display.getText());
                // Remove the positive or negative sign
                positiveOrNegativeInteger = positiveOrNegativeInteger * (-1);
                // Set the value of local variable called positiveOrNegativeInteger to the jtxtfield_Display
                jtxtfield_Display.setText(String.valueOf(positiveOrNegativeInteger));

                // If the value of field called isjbtnDotClicked is true
            } else {
                // Assign the value of local variable called positiveOrNegativeDouble to the converted value from string to double 
                positiveOrNegativeDouble = (Double.parseDouble(String.valueOf(jtxtfield_Display.getText())));
                // Remove the positive or negative sign
                positiveOrNegativeDouble = positiveOrNegativeDouble * (-1);
                // Set the value of local variable called positiveOrNegativeDouble to the jtxtfield_Display
                jtxtfield_Display.setText(String.valueOf(positiveOrNegativeDouble));
            }
        }
    }//GEN-LAST:event_jbtn_PositiveOrNegativeActionPerformed

    private void jbtn_PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_PlusActionPerformed
        // Invoke the User Defined Method called validationForarithmeticOperator and pass an argument of '+'
        validationForArithmeticOperator('+');
    }//GEN-LAST:event_jbtn_PlusActionPerformed
    private void jbtn_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_MinusActionPerformed
        // Invoke the User Defined Method called validationForarithmeticOperator and pass an argument of '-'
        validationForArithmeticOperator('-');
    }//GEN-LAST:event_jbtn_MinusActionPerformed
    private void jbtn_MutiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_MutiplyActionPerformed
        // Invoke the User Defined Method called validationForarithmeticOperator and pass an argument of '*'
        validationForArithmeticOperator('*');
    }//GEN-LAST:event_jbtn_MutiplyActionPerformed
    private void jbtn_DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DivideActionPerformed
        // Invoke the User Defined Method called validationForarithmeticOperator and pass an argument of '/'
        validationForArithmeticOperator('/');
    }//GEN-LAST:event_jbtn_DivideActionPerformed
    private void jbtn_EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_EqualActionPerformed
        // Invoke the User Defined Method called calculateTheAnswer()
        calculateTheAnswer();
    }//GEN-LAST:event_jbtn_EqualActionPerformed

    private void jbtn_EraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_EraseActionPerformed
        // If the text value of jtxtfield_Display is not empty
        if (!jtxtfield_Display.getText().equals("")) {
            // Remove one digit on it
            jtxtfield_Display.setText(jtxtfield_Display.getText().substring(0, jtxtfield_Display.getText().length() - 1));
        }
        // If the text value of jtxtfield_Display is empty
        if (jtxtfield_Display.getText().equals("")) {
            // Invoke the User Defined Method called reset()
            reset();
        }
        // If jtxtfield_Display contains commas and the value of field called isjbtnDotClicked is true
        if (jtxtfield_Display.getText().contains(".") && isDotButtonClicked == true) {
            // Changing the value of field called isjbtnDotClicked to false
            isDotButtonClicked = false;
        }
        // Invoke the User Defined Method called removingCommasAndPutBackItAgain()
        removingCommasAndPutBackItAgain();
    }//GEN-LAST:event_jbtn_EraseActionPerformed
    private void jbtn_CopyToClipBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_CopyToClipBoardActionPerformed
        // Create an object called stringSelection
        StringSelection stringSelection = new StringSelection(jtxtfield_Display.getText());
        // Create an object called clipBoard 
        Clipboard clipBoard = Toolkit.getDefaultToolkit().getSystemClipboard();
        // Set the value of object called clipBoard to null and get the value of object called stringSelection
        clipBoard.setContents(stringSelection, null);
        // Show this message dialog box
        JOptionPane.showMessageDialog(this, "SUCCESSFULLY COPIED!", "ATTENTIOM", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtn_CopyToClipBoardActionPerformed
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="User Defined Methods">
    private void setIcon() {
        // Get the image from the resouce and the filename of image is CALCULATORICON 
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("CALCULATORICON.png")));
    }

    private void reset() {
        // Assign the value of field called firstNum to 0
        firstNum = 0;
        // Assign the value of field called secondNum to 0
        secondNum = 0;
        // Assign the value of field called answer to 0
        answer = 0;
        // Assign the value of field called isjbtnDotClicked to false
        isDotButtonClicked = false;
        // Assign the value of field called arithmeticOperator to 'N'. N stands for Nothing
        arithmeticOperator = 'N';
        // Assign the value of field called isNumericButtonClicked to false
        isNumericButtonClicked = false;
        // Set the text value of jTextField called jtxtfield_Display to 0
        jtxtfield_Display.setText("0");
    }

    private String insertCommas(String param_InputNumbers) {
        // Initialize a local variable called wholeNumber
        String wholeNumber = "";
        // Get the 1st character of string parameter called param_InputNumbers
        Character firstChar = param_InputNumbers.charAt(0);
        // If there is a negative number sign
        if (firstChar == '-') {

            // Re assign the '-' to local variable called wholeNumber
            wholeNumber = wholeNumber + Character.toString(firstChar);

            // Remove all '-' string from string parameter called param_InputNumbers
            param_InputNumbers = param_InputNumbers.replaceAll("[-]", "");
        }

        // Separate the value of string parameter called param_InputNumbers each '.'
        String[] splittedNumbersArray = param_InputNumbers.split("\\.");
        // Initialize a local variable called decimalNumber
        String decimalNumber = "";

        // If the value of param_InputNumbers has decimal places
        if (splittedNumbersArray.length == 2) {
            // Re assign the value of param_InputNumbers of the 1st value of array called splittedNumbersArray  
            param_InputNumbers = splittedNumbersArray[0];
            // Re assign the value of param_InputNumbers of the 2nd value of array called splittedNumbersArray    
            decimalNumber = "." + splittedNumbersArray[1];
        }

        // THIS IS THE MAIN LOGIC FOR ADDING COMMAS TO THE NUMBER.
        // Declare a field called numberLength and assign it to the length value of param_InputNumbers
        int numberLength = param_InputNumbers.length();
        // If the condition is true, that the local variable called x is less than in field called numLength. Increment until the condition become false
        for (int x = 0; x < numberLength; x = x + 1) {
            // In every 3 digits   
            if ((numberLength - x) % 3 == 0 && x != 0) {
                // Add Comma
                wholeNumber += ",";
            }
            // Concatenate the 1st character of string parameter called param_InputNumbers to the local variable called wholeNumber
            wholeNumber += param_InputNumbers.charAt(x);
        }
        // Concatenate this 2 local variables and return the value of it 
        return wholeNumber + decimalNumber;
    }

    private void validation(int param_NumberValue) {
        // If the value of jtxtfield_Display is 0
        if (jtxtfield_Display.getText().equals("0")) {
            // Then set the value of jtxtfield_Display to empty
            jtxtfield_Display.setText("");
            // Set the value of param_NumberValue to jtxtfield_Display
            jtxtfield_Display.setText(jtxtfield_Display.getText() + param_NumberValue);
        } // If the value of jtxtfield_Display is not zero and the value of arithmeticOperator is 'N'
        else if (!jtxtfield_Display.getText().equals("0") && arithmeticOperator == 'N') {
            // Set the value of param_NumberValue to jtxtfield_Display
            jtxtfield_Display.setText(jtxtfield_Display.getText() + param_NumberValue);
        } // If the value of jtxtfield_Display is not zero and the value of arithmeticOperator is not 'N'
        else if (!jtxtfield_Display.getText().equals("0") && arithmeticOperator != 'N') {
            // If the value of isNumericButtonClicked is false
            if (isNumericButtonClicked == false) {
                // Then set the value of jtxtfield_Display to empty
                jtxtfield_Display.setText("");
                // Set the value of param_NumberValue to jtxtfield_Display
                jtxtfield_Display.setText(jtxtfield_Display.getText() + param_NumberValue);
                // Change the value of isNumericButtonClicked from false to true 
                isNumericButtonClicked = true;
            } // If the value of isNumericButtonClicked is true
            else {
                // Set the value of param_NumberValue in jtxtfield_Display
                jtxtfield_Display.setText(jtxtfield_Display.getText() + param_NumberValue);
            }
        }
        // Invoke the User Defined Method called removingCommasAndPutBackItAgain() 
        removingCommasAndPutBackItAgain();
    }

    private void removingCommasAndPutBackItAgain() {
        // Declare a local variable called removedCommas and assign it to null
        String removedCommas = null;
        // Change the value of removedCommas to the text value of JTextField called jtxtfield_Display  
        removedCommas = jtxtfield_Display.getText();

        // If the jtxtfield_Display contains "," 
        if (jtxtfield_Display.getText().contains(",")) {
            // Remove all the commas
            removedCommas = jtxtfield_Display.getText().replace(",", "");
        }

        // Declare a local variable called convertedValue and invoke the User Defined Method called insertCommas() and pass value for an argument
        String convertedValue = insertCommas(removedCommas);
        // Set the text value of jtxtfield_Display of local variable called convertedValue 
        jtxtfield_Display.setText(convertedValue);
    }

    private void validationForArithmeticOperator(char param_arithmeticOperator) {
        // Declare a local variable called removedCommas and assign it to null
        String removedCommas = null;
        // Change the value of local variable called removedCommas to the value of jtxtfield_Display 
        removedCommas = jtxtfield_Display.getText();

        // If the jtxtfield_Display contains ","
        if (jtxtfield_Display.getText().contains(",")) {
            // Remove all the commas
            removedCommas = jtxtfield_Display.getText().replace(",", "");
        }

        // If value of field called arithmeticOperator is N 
        if (arithmeticOperator == 'N') {
            // Change the value of field called firstNum to the converted field called removedCommas 
            firstNum = (Double.parseDouble(String.valueOf(removedCommas)));
            // Set the value of field called arithmeticOperator to the string parameter called param_arithmeticOperator 
            arithmeticOperator = param_arithmeticOperator;

            // If the value of field called answer is 0 
        } else if (answer == 0) {
            // Change the value of field called firstNum to the converted field called removedCommas 
            firstNum = (Double.parseDouble(String.valueOf(removedCommas)));
            // Invoke the User Defined Method called calculateTheAnswer()
            calculateTheAnswer();

            // If the value of field called answer is not 0 
        } else if (answer != 0) {
            // Change the value of field called firstNum to the converted field called answer 
            firstNum = (Double.parseDouble(String.valueOf(answer)));
            // Invoke the User Defined Method called calculateTheAnswer()
            calculateTheAnswer();
        }

        // Change the value of field called isNumericButtonClicked to false
        isNumericButtonClicked = false;
    }

    private void calculateTheAnswer() {
        // If the text of value of is not zero and don't have "."
        if (!jtxtfield_Display.getText().equals("0") && !jtxtfield_Display.getText().equals(".")) {
            // Declare a local variable called removedCommas and assign it to null
            String removedCommas = null;
            // Change the value of local variable called removedCommas to the value of jtxtfield_Display 
            removedCommas = jtxtfield_Display.getText();

            // If jtxtfield_Display contains commas
            if (jtxtfield_Display.getText().contains(",")) {
                // Remove all commas
                removedCommas = jtxtfield_Display.getText().replace(",", "");
            }
            // Changing the value of field called secondNum to the converted field called removedCommas
            secondNum = (Double.parseDouble(String.valueOf(removedCommas)));

            // Check the value of field called arithmeticOperator
            switch (arithmeticOperator) {

                case '+': // If the value is +    
                    answer = firstNum + secondNum;  // Then add the two fields
                    break;
                case '-': // If the value is -
                    answer = firstNum - secondNum; // Then subract the two fields
                    break;
                case '*': // If the value is *
                    answer = firstNum * secondNum; // Then Times the two fields
                    break;
                case '/': // If the value is /
                    answer = firstNum / secondNum; // Then Divide the two fields
                    break;
            }

            // If the value of field called isjbtnDotClicked is true
            if (isDotButtonClicked == true) {
                // Set the value of field called answer to jtxtfield_Display
                jtxtfield_Display.setText(String.valueOf(answer));

                // If the value of field called isjbtnDotClicked is false
            } else if (isDotButtonClicked == false) {
                // Declare a local variable called convertedAnswer that will hold the value of converted field called answer
                int convertedAnswer = (int) answer;
                // Set the value of field called answer to jtxtfield_Display
                jtxtfield_Display.setText(String.valueOf(convertedAnswer));
            }

            // Declaring a local variable called convertedValue and calling the User Defined Method called insertCommas() and pass an argument for the method parameter of it 
            String convertedValue = insertCommas(jtxtfield_Display.getText());
            // Set the text value of jtxtfield_Display of local variable called convertedValue 
            jtxtfield_Display.setText(convertedValue);
        }
    }
    // </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_Clear;
    private javax.swing.JButton jbtn_Close;
    private javax.swing.JButton jbtn_CopyToClipBoard;
    private javax.swing.JButton jbtn_Divide;
    private javax.swing.JButton jbtn_Dot;
    private javax.swing.JButton jbtn_Eight;
    private javax.swing.JButton jbtn_Equal;
    private javax.swing.JButton jbtn_Erase;
    private javax.swing.JButton jbtn_Five;
    private javax.swing.JButton jbtn_Four;
    private javax.swing.JButton jbtn_Minimize;
    private javax.swing.JButton jbtn_Minus;
    private javax.swing.JButton jbtn_Mutiply;
    private javax.swing.JButton jbtn_Nine;
    private javax.swing.JButton jbtn_One;
    private javax.swing.JButton jbtn_Plus;
    private javax.swing.JButton jbtn_PositiveOrNegative;
    private javax.swing.JButton jbtn_Seven;
    private javax.swing.JButton jbtn_Six;
    private javax.swing.JButton jbtn_Three;
    private javax.swing.JButton jbtn_Two;
    private javax.swing.JButton jbtn_Zero;
    private javax.swing.JLabel jlbl_Title;
    private javax.swing.JPanel jpanel_Main;
    private javax.swing.JTextField jtxtfield_Display;
    // End of variables declaration//GEN-END:variables
}
